# Generated by Django 5.2.3 on 2025-06-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(default="pendiente", max_length=75),
        ),
    ]
